apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-1dlf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-service-e2e-tenant/appstudio/dc-metro-map-1dlf@sha256:3983a276dd74b0d832d711236b98b05fa5e7548d623d1d061d5fe434f8287770
        name: my-nodejs
        resources: {}
status: {}
