apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-1dlf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-1dlf
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-1dlf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-1dlf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-1dlf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-service-e2e-tenant/appstudio/dc-metro-map-1dlf@sha256:3983a276dd74b0d832d711236b98b05fa5e7548d623d1d061d5fe434f8287770
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
